version: "3.8"
services:
  firebase:
    image: google/cloud-sdk:476.0.0
    command: gcloud emulators firestore start --host-port=0.0.0.0:8978
    ports:
      - "8978:8978"
    
  datastore:
    image: google/cloud-sdk:476.0.0
    command: gcloud emulators firestore start --database-mode=datastore-mode --host-port=0.0.0.0:8380
    ports:
      - "8380:8380"

  benchmark:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      FIRESTORE_EMULATOR_HOST: statestorebenchmark-firebase-1:8978
      PROJECT_ID: knp-ok-app-test